import { useMemo, useState } from "react";
import { ArrowLeft, BellRing, Check, CheckCircle2, ClipboardList, FileText, RotateCcw, ShieldAlert, X } from "lucide-react";
import { aprovacoesMock, contratosMock, documentosMock, processosRHMock, type AprovacaoMock, type ProcessoRHMock } from "@/data/mockAdministrativo";
import { AutomacoesAdministrativo } from "@/components/AutomacoesAdministrativo";

type Props = { onVoltar: () => void; perfil?: "Administrador" | "Administrativo" };

export function AdministrativoDashboard({ onVoltar, perfil = "Administrativo" }: Props) {
  const [aprovacoes, setAprovacoes] = useState<AprovacaoMock[]>(aprovacoesMock);
  const [processosRH, setProcessosRH] = useState<ProcessoRHMock[]>(processosRHMock);
  const [mensagem, setMensagem] = useState("Rotina diária executada: 4 documentos verificados e 2 contratos analisados.");
  const sla = useMemo(() => ({ vencidos: documentosMock.filter((d) => (d.diasParaVencer ?? 1) < 0).length, vencer: documentosMock.filter((d) => (d.diasParaVencer ?? 31) >= 0 && (d.diasParaVencer ?? 31) <= 30).length, contratos: contratosMock.length, aprovacoes: aprovacoes.filter((a) => a.status === "Pendente").length }), [aprovacoes]);
  const decidir = (id: string, status: "Aprovado" | "Rejeitado") => setAprovacoes((itens) => itens.map((item) => item.id === id ? { ...item, status } : item));
  const alternarItem = (processoId: string, indice: number) => setProcessosRH((processos) => processos.map((processo) => processo.id !== processoId ? processo : { ...processo, itens: processo.itens.map((item, i) => i === indice ? { ...item, concluido: !item.concluido } : item) }));
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-800 sm:p-8"><header className="mx-auto flex max-w-7xl flex-col gap-4 rounded-3xl bg-slate-900 p-6 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><img src="/logo-eg.jpeg" alt="Logo EG" className="h-16 w-16 rounded-xl bg-white object-contain p-1" /><div><p className="text-xs font-bold tracking-[0.2em] text-amber-300">ELETROGESTOR</p><h1 className="mt-2 text-3xl font-bold">{perfil}</h1><p className="mt-1 text-sm text-slate-300">Automações administrativas com base fictícia para validação.</p></div></div><button onClick={onVoltar} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-600 px-4 py-2 text-sm font-semibold hover:bg-slate-800"><ArrowLeft className="h-4 w-4" /> Perfis</button></header>
    <section className="mx-auto mt-7 max-w-7xl"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><SlaCard numero={sla.vencidos} titulo="Documentos vencidos" cor="text-red-700" /><SlaCard numero={sla.vencer} titulo="Vencem em até 30 dias" cor="text-amber-700" /><SlaCard numero={sla.contratos} titulo="Contratos a vencer" cor="text-blue-700" /><SlaCard numero={sla.aprovacoes} titulo="Aprovações pendentes" cor="text-violet-700" /></div><div className="mt-5 flex flex-col gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900 sm:flex-row sm:items-center sm:justify-between"><span><BellRing className="mr-2 inline h-4 w-4" />{mensagem}</span><button onClick={() => setMensagem("Rotina diária executada agora: alertas de vencimento, vigência e backup simulados.")} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white hover:bg-emerald-800"><RotateCcw className="mr-1 inline h-3.5 w-3.5" /> Executar rotina diária</button></div></section>
    <section className="mx-auto mt-6 grid max-w-7xl gap-5 xl:grid-cols-2"><PainelDocumentos /><PainelAprovacoes itens={aprovacoes} decidir={decidir} /><PainelRH processos={processosRH} alternar={alternarItem} /><PainelIntegracoes /></section><AutomacoesAdministrativo />
  </main>;
}

function SlaCard({ numero, titulo, cor }: { numero: number; titulo: string; cor: string }) { return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className={`text-3xl font-bold ${cor}`}>{numero}</p><p className="mt-1 text-sm text-slate-500">{titulo}</p></div>; }
function PainelDocumentos() { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><ShieldAlert className="h-5 w-5 text-amber-600" /> Documentos e contratos</h2><div className="mt-4 space-y-2">{documentosMock.map((doc) => <div key={doc.id} className={`rounded-xl p-3 text-sm ${doc.diasParaVencer !== null && doc.diasParaVencer < 0 ? "bg-red-50 text-red-800" : "bg-amber-50 text-amber-800"}`}><b>{doc.tipo}</b> — {doc.titular}<span className="float-right text-xs font-bold">{doc.diasParaVencer !== null && doc.diasParaVencer < 0 ? `${Math.abs(doc.diasParaVencer)} dias vencido` : `vence em ${doc.diasParaVencer} dias`}</span></div>)}</div><h3 className="mt-5 text-sm font-bold">Vigência de contratos</h3><div className="mt-2 space-y-2">{contratosMock.map((contrato) => <p key={contrato.id} className="rounded-xl border border-slate-200 p-3 text-sm"><b>{contrato.fornecedor}</b> — {contrato.objeto}<br /><span className="text-xs text-slate-500">Vence em {contrato.diasParaVencer} dias · Renovação automática: {contrato.renovacaoAutomatica ? "sim" : "não"}</span></p>)}</div></section>; }
function PainelAprovacoes({ itens, decidir }: { itens: AprovacaoMock[]; decidir: (id: string, status: "Aprovado" | "Rejeitado") => void }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><ClipboardList className="h-5 w-5 text-violet-600" /> Fluxo de aprovações</h2><p className="mt-1 text-sm text-slate-500">Aprove ou rejeite para atualizar o SLA de forma imediata.</p><div className="mt-4 space-y-3">{itens.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><b className="text-sm">{item.titulo}</b><p className="mt-1 text-xs text-slate-500">{item.solicitante} → {item.aprovador}</p></div><Status status={item.status} /></div>{item.status === "Pendente" && <div className="mt-3 flex gap-2"><button onClick={() => decidir(item.id, "Aprovado")} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-bold text-white hover:bg-emerald-700"><Check className="mr-1 inline h-3.5 w-3.5" /> Aprovar</button><button onClick={() => decidir(item.id, "Rejeitado")} className="rounded-lg bg-red-100 px-3 py-1.5 text-xs font-bold text-red-700 hover:bg-red-200"><X className="mr-1 inline h-3.5 w-3.5" /> Rejeitar</button></div>}</div>)}</div></section>; }
function Status({ status }: { status: AprovacaoMock["status"] }) { const estilos = { Pendente: "bg-amber-100 text-amber-700", Aprovado: "bg-emerald-100 text-emerald-700", Rejeitado: "bg-red-100 text-red-700" }; return <span className={`h-fit rounded-full px-2 py-1 text-xs font-bold ${estilos[status]}`}>{status}</span>; }
function PainelRH({ processos, alternar }: { processos: ProcessoRHMock[]; alternar: (id: string, indice: number) => void }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><CheckCircle2 className="h-5 w-5 text-emerald-600" /> Admissão e demissão</h2><p className="mt-1 text-sm text-slate-500">Checklist de RH com estado salvo apenas nesta demonstração.</p><div className="mt-4 space-y-4">{processos.map((processo) => <div key={processo.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between"><b>{processo.colaborador}</b><span className="text-xs font-bold text-slate-500">{processo.tipo}</span></div>{processo.itens.map((item, indice) => <button key={item.descricao} onClick={() => alternar(processo.id, indice)} className="mt-3 flex w-full items-center gap-2 text-left text-sm"><span className={`flex h-5 w-5 items-center justify-center rounded border ${item.concluido ? "border-emerald-600 bg-emerald-600 text-white" : "border-slate-300 bg-white"}`}>{item.concluido && <Check className="h-3.5 w-3.5" />}</span><span className={item.concluido ? "text-slate-400 line-through" : "text-slate-700"}>{item.descricao}</span></button>)}</div>)}</div></section>; }
function PainelIntegracoes() {
  const [relatorio, setRelatorio] = useState<{ periodo: string; geradoEm: string } | null>(null);
  const baixarWord = () => {
    if (!relatorio) return;
    const conteudo = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Relatório Administrativo</title><style>body{font-family:Arial,sans-serif;color:#1e293b;margin:48px}h1{font-size:24px}h2{font-size:16px;margin-top:28px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #cbd5e1;padding:8px;text-align:left}th{background:#f1f5f9}</style></head><body><h1>Relatório Administrativo EletroGestor</h1><p><b>Periodicidade:</b> ${relatorio.periodo}</p><p><b>Gerado em:</b> ${relatorio.geradoEm}</p><h2>Resumo de pendências</h2><table><tr><th>Indicador</th><th>Quantidade</th></tr><tr><td>Documentos vencidos</td><td>${documentosMock.filter((d) => (d.diasParaVencer ?? 1) < 0).length}</td></tr><tr><td>Documentos a vencer em 30 dias</td><td>${documentosMock.filter((d) => (d.diasParaVencer ?? 31) >= 0 && (d.diasParaVencer ?? 31) <= 30).length}</td></tr><tr><td>Contratos a vencer</td><td>${contratosMock.length}</td></tr><tr><td>Aprovações pendentes</td><td>${aprovacoesMock.filter((a) => a.status === "Pendente").length}</td></tr></table><h2>Observação</h2><p>Relatório gerado a partir da base fictícia de demonstração do EletroGestor.</p></body></html>`;
    const arquivo = new Blob(["\ufeff", conteudo], { type: "application/msword" });
    const url = URL.createObjectURL(arquivo);
    const link = document.createElement("a");
    link.href = url;
    link.download = `relatorio-administrativo-${relatorio.periodo.toLowerCase()}.doc`;
    link.click();
    URL.revokeObjectURL(url);
  };
  return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><FileText className="h-5 w-5 text-blue-600" /> Relatórios e integrações</h2><div className="mt-4 grid gap-2 sm:grid-cols-3">{["Diário", "Semanal", "Mensal"].map((periodo) => <button key={periodo} onClick={() => setRelatorio({ periodo, geradoEm: new Date().toLocaleString("pt-BR") })} className="rounded-xl bg-blue-50 px-3 py-3 text-sm font-bold text-blue-700 hover:bg-blue-100">Gerar {periodo}</button>)}</div>{relatorio && <div className="mt-3 flex flex-col gap-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800 sm:flex-row sm:items-center sm:justify-between"><span>Relatório {relatorio.periodo.toLowerCase()} gerado com dados fictícios.</span><button onClick={baixarWord} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white hover:bg-blue-800">Baixar em Word</button></div>}<div className="mt-5 rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-600"><b>Integrações externas</b><p className="mt-1">NFS-e/SEFAZ, Receita Federal (CPF/CNPJ), OCR e backup estão preparados como fluxos, mas aguardam credenciais e APIs reais.</p></div></section>;
}
