import { useMemo, useState } from "react";
import { Activity, ArrowLeft, Check, Database, KeyRound, ListChecks, Settings2, ShieldCheck, ToggleLeft, Users } from "lucide-react";
import { GovernancaAutomacoes } from "@/components/GovernancaAutomacoes";

type Props = { onVoltar: () => void };
type Usuario = { id: string; nome: string; email: string; perfil: string; status: "Ativo" | "Inativo" | "Bloqueado"; ultimoAcesso: string };
type Modulo = { id: string; nome: string; categoria: string; ativo: boolean };
const usuariosIniciais: Usuario[] = [
  { id: "u1", nome: "Maria Souza", email: "maria@eletrogestor.com", perfil: "Gerência Geral", status: "Ativo", ultimoAcesso: "Hoje, 08:42" },
  { id: "u2", nome: "João Silva", email: "joao@eletrogestor.com", perfil: "Equipe de Campo", status: "Ativo", ultimoAcesso: "Hoje, 07:15" },
  { id: "u3", nome: "Carlos Lima", email: "carlos@eletrogestor.com", perfil: "Supervisor", status: "Bloqueado", ultimoAcesso: "Ontem, 18:10" },
];
const modulosIniciais: Modulo[] = [
  { id: "m1", nome: "Programação de Obras", categoria: "Operação", ativo: true },
  { id: "m2", nome: "Gerência Geral", categoria: "Gestão", ativo: true },
  { id: "m3", nome: "Administrativo", categoria: "Gestão", ativo: true },
  { id: "m4", nome: "Faturamento e Medição", categoria: "Gestão", ativo: true },
  { id: "m5", nome: "Segurança do Trabalho", categoria: "Suporte", ativo: true },
  { id: "m6", nome: "Self Healing", categoria: "Técnico", ativo: false },
];

export function AdministradorDashboard({ onVoltar }: Props) {
  const [usuarios, setUsuarios] = useState<Usuario[]>(usuariosIniciais);
  const [modulos, setModulos] = useState<Modulo[]>(modulosIniciais);
  const [parametros, setParametros] = useState({ preApr: 45, backup: "02:00", email: true, whatsapp: false, fiscal: false, enel: false });
  const [auditoria, setAuditoria] = useState(["08:42 — maria@eletrogestor.com realizou login", "08:20 — sistema executou backup de 12 itens", "07:15 — joao@eletrogestor.com realizou login", "Ontem 18:10 — carlos@eletrogestor.com foi bloqueado após 5 tentativas"]);
  const [backup, setBackup] = useState("Último backup: hoje às 02:00 — 12 itens versionados — sucesso");
  const resumo = useMemo(() => ({ usuarios: usuarios.length, ativos: modulos.filter((m) => m.ativo).length, falhas: usuarios.filter((u) => u.status === "Bloqueado").length }), [usuarios, modulos]);
  const alternarUsuario = (id: string) => setUsuarios((lista) => lista.map((u) => u.id === id ? { ...u, status: u.status === "Ativo" ? "Inativo" : "Ativo" } : u));
  const resetar = (usuario: Usuario) => { setUsuarios((lista) => lista.map((u) => u.id === usuario.id ? { ...u, status: "Ativo" } : u)); setAuditoria((log) => [`Agora — senha de ${usuario.email} redefinida e usuário liberado`, ...log]); };
  const alternarModulo = (id: string) => { const modulo = modulos.find((m) => m.id === id); setModulos((lista) => lista.map((m) => m.id === id ? { ...m, ativo: !m.ativo } : m)); if (modulo) setAuditoria((log) => [`Agora — módulo ${modulo.nome} ${modulo.ativo ? "desativado" : "ativado"}`, ...log]); };
  const executarBackup = () => { setBackup("Último backup: agora — 18 itens versionados — sucesso"); setAuditoria((log) => ["Agora — backup manual executado com sucesso", ...log]); };
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-800 sm:p-8"><header className="mx-auto flex max-w-7xl flex-col gap-4 rounded-3xl bg-slate-900 p-6 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><img src="/logo-eg.jpeg" alt="Logo EG" className="h-16 w-16 rounded-xl bg-white object-contain p-1" /><div><p className="text-xs font-bold tracking-[0.2em] text-amber-300">ELETROGESTOR</p><h1 className="mt-2 text-3xl font-bold">Administrador</h1><p className="mt-1 text-sm text-slate-300">Controle de usuários, permissões, sistema e manutenção.</p></div></div><button onClick={onVoltar} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-600 px-4 py-2 text-sm font-semibold hover:bg-slate-800"><ArrowLeft className="h-4 w-4" /> Perfis</button></header>
    <section className="mx-auto mt-7 grid max-w-7xl gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card numero={resumo.usuarios} texto="usuários cadastrados" cor="text-blue-700" /><Card numero="21" texto="perfis configurados" cor="text-violet-700" /><Card numero={resumo.ativos} texto="módulos ativos" cor="text-emerald-700" /><Card numero={resumo.falhas} texto="bloqueios de acesso" cor="text-red-700" /></section>
    <section className="mx-auto mt-6 grid max-w-7xl gap-5 xl:grid-cols-2"><PainelUsuarios usuarios={usuarios} alternar={alternarUsuario} resetar={resetar} /><PainelModulos modulos={modulos} alternar={alternarModulo} /><PainelParametros parametros={parametros} setParametros={setParametros} auditoria={() => setAuditoria((log) => ["Agora — parâmetros do sistema atualizados", ...log])} /><PainelBackup backup={backup} executar={executarBackup} /><PainelAuditoria itens={auditoria} /></section>
    <GovernancaAutomacoes />
  </main>;
}
function Card({ numero, texto, cor }: { numero: number | string; texto: string; cor: string }) { return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className={`text-3xl font-bold ${cor}`}>{numero}</p><p className="mt-1 text-sm text-slate-500">{texto}</p></div>; }
function PainelUsuarios({ usuarios, alternar, resetar }: { usuarios: Usuario[]; alternar: (id: string) => void; resetar: (u: Usuario) => void }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><Users className="h-5 w-5 text-blue-600" /> Gestão de usuários</h2><div className="mt-4 space-y-3">{usuarios.map((u) => <div key={u.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-3"><div><b className="text-sm">{u.nome}</b><p className="text-xs text-slate-500">{u.email} · {u.perfil}</p></div><Status status={u.status} /></div><p className="mt-2 text-xs text-slate-500">Último acesso: {u.ultimoAcesso}</p><div className="mt-3 flex gap-2"><button onClick={() => alternar(u.id)} className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-xs font-bold text-slate-700">{u.status === "Ativo" ? "Desativar" : "Ativar"}</button><button onClick={() => resetar(u)} className="rounded-lg bg-blue-600 px-2.5 py-1.5 text-xs font-bold text-white"><KeyRound className="mr-1 inline h-3 w-3" /> Resetar senha</button></div></div>)}</div></section>; }
function Status({ status }: { status: Usuario["status"] }) { const cor = { Ativo: "bg-emerald-100 text-emerald-700", Inativo: "bg-slate-100 text-slate-600", Bloqueado: "bg-red-100 text-red-700" }[status]; return <span className={`h-fit rounded-full px-2 py-1 text-xs font-bold ${cor}`}>{status}</span>; }
function PainelModulos({ modulos, alternar }: { modulos: Modulo[]; alternar: (id: string) => void }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><ToggleLeft className="h-5 w-5 text-violet-600" /> Módulos e permissões</h2><p className="mt-1 text-sm text-slate-500">Ative ou desative módulos do sistema.</p><div className="mt-4 space-y-2">{modulos.map((m) => <div key={m.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span><b className="text-sm">{m.nome}</b><small className="ml-2 text-slate-500">{m.categoria}</small></span><button onClick={() => alternar(m.id)} className={`rounded-full px-3 py-1 text-xs font-bold ${m.ativo ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{m.ativo ? "Ativo" : "Inativo"}</button></div>)}</div></section>; }
function PainelParametros({ parametros, setParametros, auditoria }: { parametros: { preApr: number; backup: string; email: boolean; whatsapp: boolean; fiscal: boolean; enel: boolean }; setParametros: (p: { preApr: number; backup: string; email: boolean; whatsapp: boolean; fiscal: boolean; enel: boolean }) => void; auditoria: () => void }) { const alterar = <K extends keyof typeof parametros>(chave: K, valor: typeof parametros[K]) => setParametros({ ...parametros, [chave]: valor }); return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><Settings2 className="h-5 w-5 text-amber-600" /> Parâmetros do sistema</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Alerta Pré APR (dias)<input value={parametros.preApr} type="number" onChange={(e) => alterar("preApr", Number(e.target.value))} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Horário do backup<input value={parametros.backup} onChange={(e) => alterar("backup", e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm">{(["email", "whatsapp", "fiscal", "enel"] as const).map((chave) => <button key={chave} onClick={() => alterar(chave, !parametros[chave])} className={`rounded-lg p-2 text-left font-bold ${parametros[chave] ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{chave === "enel" ? "Integração Enel" : chave === "fiscal" ? "Integração fiscal" : chave === "email" ? "E-mail" : "WhatsApp"}: {parametros[chave] ? "ativa" : "inativa"}</button>)}</div><button onClick={auditoria} className="mt-4 rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white"><Check className="mr-1 inline h-3.5 w-3.5" /> Salvar parâmetros</button></section>; }
function PainelBackup({ backup, executar }: { backup: string; executar: () => void }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><Database className="h-5 w-5 text-emerald-600" /> Backup e manutenção</h2><p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{backup}</p><button onClick={executar} className="mt-4 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Executar backup agora</button><p className="mt-3 text-xs text-slate-500">Restauração real será conectada ao armazenamento na próxima etapa.</p></section>; }
function PainelAuditoria({ itens }: { itens: string[] }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 xl:col-span-2"><h2 className="flex items-center gap-2 font-bold"><Activity className="h-5 w-5 text-slate-700" /> Log de auditoria</h2><div className="mt-4 space-y-2">{itens.map((item, i) => <p key={`${item}-${i}`} className="rounded-lg border border-slate-200 p-3 text-sm">{item}</p>)}</div></section>; }
