import { useState } from "react";
import { BellRing, FileDown, ShieldCheck, UserRoundPlus } from "lucide-react";
import { faturasIniciais, medicoesIniciais } from "@/data/faturamentoService";

export function AutomacoesAdministrativo() {
  const [form, setForm] = useState({ nome: "", documento: "", obra: "" }); const [aviso, setAviso] = useState(""); const [etapa, setEtapa] = useState(0);
  const baixar = (titulo: string, linhas: string[]) => { const html = `<html><body><h1>${titulo}</h1>${linhas.map((l) => `<p>${l}</p>`).join("")}</body></html>`; const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([html], { type: "application/pdf" })); a.download = `${titulo.replace(/ /g, "-")}.pdf`; a.click(); };
  const cadastrar = () => { const doc = form.documento.replace(/\D/g, ""); if (doc.length !== 11 && doc.length !== 14) return setAviso("CPF/CNPJ inválido."); if (["12345678000190", "98765432000110"].includes(doc)) return setAviso("Cadastro duplicado bloqueado: CPF/CNPJ já existe na fonte única de Faturamento."); setAviso("Cliente e obra cadastrados na fonte compartilhada com Faturamento/Medição."); };
  const medicao = medicoesIniciais[1]; const fatura = faturasIniciais[0];
  return <section className="mx-auto mt-6 max-w-7xl rounded-3xl border border-blue-200 bg-blue-50/50 p-5"><h2 className="text-2xl font-bold">Automações documentais</h2><p className="mt-1 text-sm text-slate-600">Documentos, cadastros e aprovações com base compartilhada.</p><div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><FileDown /> PDFs automáticos</h3><p className="mt-2 text-sm">Medição e fatura do serviço Faturamento/Medição.</p><button onClick={() => baixar("Termo de Medicao", [`Obra: ${medicao.obra}`, `Percentual: ${medicao.percentual}%`, `Responsável: ${medicao.responsavel}`])} className="mt-3 rounded bg-blue-700 px-3 py-2 text-xs font-bold text-white">Gerar termo PDF</button><button onClick={() => baixar("Recibo de Cobranca", [`Obra: ${fatura.obra}`, `Fatura: ${fatura.id}`, `Valor: R$ ${fatura.valor}`])} className="ml-2 mt-3 rounded bg-slate-800 px-3 py-2 text-xs font-bold text-white">Gerar recibo PDF</button></div><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><UserRoundPlus /> Cadastro unificado</h3><div className="mt-3 grid gap-2 sm:grid-cols-3"><input placeholder="Cliente" value={form.nome} onChange={(e) => setForm({ ...form, nome: e.target.value })} className="border p-2" /><input placeholder="CPF/CNPJ" value={form.documento} onChange={(e) => setForm({ ...form, documento: e.target.value })} className="border p-2" /><input placeholder="Obra" value={form.obra} onChange={(e) => setForm({ ...form, obra: e.target.value })} className="border p-2" /></div><button onClick={cadastrar} className="mt-3 rounded bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Validar e salvar</button></div><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><ShieldCheck /> Aprovação contratual</h3><p className="mt-3 text-sm">Administrativo → Gerência Geral → Arquivado</p><button onClick={() => { setEtapa(Math.min(2, etapa + 1)); setAviso(etapa === 0 ? "Contrato encaminhado à Gerência Geral. Notificação enviada." : "Contrato aprovado e arquivado."); }} className="mt-3 rounded bg-violet-700 px-3 py-2 text-xs font-bold text-white">Avançar aprovação</button></div><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><BellRing /> Alertas de vigência</h3><p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-800">EPI Protege vence em 12 dias. Alerta de 30 dias ativo.</p><p className="mt-2 rounded bg-amber-50 p-3 text-sm text-amber-800">LocaFrota vence em 25 dias. Notificação enviada.</p></div></div>{aviso && <p className="mt-4 rounded bg-emerald-50 p-3 text-sm text-emerald-800">{aviso}</p>}</section>;
}
