import { useState } from "react";
import { BadgeCheck, Landmark, ShieldAlert, UserRoundCheck } from "lucide-react";
import { TETO_MAXIMO_DESCONTO_ANTECIPACAO, registrarAuditoria } from "@/data/governancaService";

export function AutomacoesFaturamento() { const [mandato, setMandato] = useState({ id: "PIX-MND-0091", ativo: true, teto: 50000 }); const [status, setStatus] = useState("Pronto para cobrança automática"); const valorFatura = 80000; const [desconto, setDesconto] = useState(4); const [conciliada, setConciliada] = useState(false); const risco = valorFatura > mandato.teto ? "alto" : "medio"; const cobrar = () => { if (!mandato.ativo) return setStatus("Mandato cancelado: régua de cobrança interrompida."); if (valorFatura > mandato.teto) { registrarAuditoria({ bot: "PIX Automático", acao: "Aguardando aprovação manual", entidade: "FAT-00087", antes: "Emitida", depois: "Aguardando aprovação", responsavel: "sistema" }); return setStatus("Aguardando aprovação manual: valor ultrapassa o teto do mandato."); } registrarAuditoria({ bot: "PIX Automático", acao: "Cobrança enviada", entidade: "FAT-00087", antes: "Emitida", depois: "Cobrança PIX criada", responsavel: "sistema" }); setStatus("Cobrança PIX automática enviada."); };
  const cancelar = () => { setMandato({ ...mandato, ativo: false }); setStatus("Callback bancário recebido: mandato cancelado e régua interrompida."); registrarAuditoria({ bot: "PIX Automático", acao: "Cancelamento de mandato", entidade: "FAT-00087", antes: "Mandato ativo", depois: "Mandato cancelado", responsavel: "sistema" }); };
  const conciliar = () => { setConciliada(true); setStatus("Webhook PIX conciliado: fatura localizada e marcada como paga."); registrarAuditoria({ bot: "Conciliação PIX", acao: "Pagamento confirmado", entidade: "FAT-00087", antes: "Atrasada", depois: "Paga", responsavel: "sistema" }); };
  const simular = () => { const permitido = Math.min(desconto, TETO_MAXIMO_DESCONTO_ANTECIPACAO); setDesconto(permitido); registrarAuditoria({ bot: "Desconto por antecipação", acao: "Simulação com guardrail", entidade: "FAT-00087", antes: `${desconto}%`, depois: `${permitido}%`, responsavel: "usuário" }); setStatus(`Desconto simulado em ${permitido}%. Teto do Administrador: ${TETO_MAXIMO_DESCONTO_ANTECIPACAO}%.`); };
  return <section className="mx-auto mt-6 max-w-7xl rounded-3xl border border-emerald-200 bg-emerald-50/50 p-5"><h2 className="text-2xl font-bold">PIX, cobrança e conciliação</h2><div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><Landmark /> PIX Automático</h3><p className="mt-3 text-sm">Mandato: <b>{mandato.id}</b> · {mandato.ativo ? "Ativo" : "Cancelado"} · teto: R$ {mandato.teto.toLocaleString("pt-BR")}</p><p className="mt-2 text-sm">Fatura FAT-00087: R$ {valorFatura.toLocaleString("pt-BR")}</p><button onClick={cobrar} className="mt-3 rounded bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Processar cobrança</button><button onClick={cancelar} className="ml-2 mt-3 rounded bg-red-100 px-3 py-2 text-xs font-bold text-red-700">Simular callback de cancelamento</button></div><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><ShieldAlert /> Régua segmentada</h3><p className="mt-3 text-sm">Perfil de risco da obra: <b className="uppercase text-red-700">{risco}</b></p><p className="mt-2 text-sm">Risco baixo: e-mail/WhatsApp. Risco alto: e-mail, WhatsApp e fila de contato humano.</p><p className="mt-3 rounded bg-red-50 p-3 text-sm text-red-800">Esta fatura entra na fila de contato humano por exceder o teto PIX.</p></div><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><BadgeCheck /> Guardrail de antecipação</h3><input type="number" value={desconto} onChange={(e) => setDesconto(Number(e.target.value))} className="mt-3 w-32 border p-2" /> <span className="text-sm">% solicitado</span><p className="mt-2 text-sm">Teto global do Administrador: {TETO_MAXIMO_DESCONTO_ANTECIPACAO}%.</p><button onClick={simular} className="mt-3 rounded bg-violet-700 px-3 py-2 text-xs font-bold text-white">Simular com guardrail</button></div><div className="rounded-2xl bg-white p-5"><h3 className="flex gap-2 font-bold"><UserRoundCheck /> Conciliação automática</h3><p className="mt-3 text-sm">Receba o webhook PIX e localize a fatura sem busca manual.</p><button onClick={conciliar} disabled={conciliada} className="mt-3 rounded bg-blue-700 px-3 py-2 text-xs font-bold text-white">{conciliada ? "Pagamento conciliado" : "Simular confirmação PIX"}</button></div></div><p className="mt-5 rounded bg-emerald-100 p-3 text-sm text-emerald-900">{status}</p></section>; }
