import { useMemo, useState } from "react";
import { ArrowLeft, BadgeDollarSign, Calculator, Check, FileCheck2, Send, TimerReset } from "lucide-react";
import { faturasIniciais, medicoesIniciais, type FaturaFaturamento as Fatura, type MedicaoFaturamento as Medicao } from "@/data/faturamentoService";
import { AutomacoesFaturamento } from "@/components/AutomacoesFaturamento";

type Props = { onVoltar: () => void };
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export function FaturamentoDashboard({ onVoltar }: Props) {
  const [medicoes, setMedicoes] = useState(medicoesIniciais); const [faturas, setFaturas] = useState(faturasIniciais); const [mensagem, setMensagem] = useState("Base fictícia de faturamento carregada."); const [simulacao, setSimulacao] = useState<string | null>(null);
  const resumo = useMemo(() => ({ faturado: faturas.reduce((s, f) => s + f.valor, 0), pago: faturas.filter((f) => f.status === "Paga").reduce((s, f) => s + f.valor, 0), pendente: faturas.filter((f) => f.status !== "Paga").reduce((s, f) => s + f.valor, 0), atrasadas: faturas.filter((f) => f.status === "Atrasada").length }), [faturas]);
  const aprovar = (id: string) => { const medicao = medicoes.find((m) => m.id === id); setMedicoes((lista) => lista.map((m) => m.id === id ? { ...m, status: "Aprovada" } : m)); if (medicao) setMensagem(`Medição de ${medicao.obra} aprovada. Agora ela pode gerar fatura.`); };
  const gerarFatura = (medicao: Medicao) => { const valor = medicao.contrato * medicao.percentual / 100; setFaturas((lista) => [...lista, { id: `fat-${Date.now()}`, obra: medicao.obra, valor, vencimento: "15/10/2026", diasAtraso: 0, status: "Emitida" }]); setMensagem(`Fatura de ${brl.format(valor)} gerada para ${medicao.obra}.`); };
  const pagar = (id: string) => { setFaturas((lista) => lista.map((f) => f.id === id ? { ...f, status: "Paga", diasAtraso: 0 } : f)); setMensagem("Pagamento registrado e status atualizado."); };
  const rodarMotor = () => { setFaturas((lista) => lista.map((f) => f.status === "Emitida" && f.vencimento === "25/09/2026" ? { ...f, status: "Atrasada", diasAtraso: 1 } : f)); setMensagem("Automação diária concluída: atrasos verificados, juros recalculados e régua de cobrança atualizada."); };
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-800 sm:p-8"><header className="mx-auto flex max-w-7xl flex-col gap-4 rounded-3xl bg-slate-900 p-6 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><img src="/logo-eg.jpeg" alt="Logo EG" className="h-16 w-16 rounded-xl bg-white object-contain p-1" /><div><p className="text-xs font-bold tracking-[0.2em] text-amber-300">ELETROGESTOR</p><h1 className="mt-2 text-3xl font-bold">Faturamento e Medição</h1><p className="mt-1 text-sm text-slate-300">Medições, faturas e automações de recebimento.</p></div></div><button onClick={onVoltar} className="inline-flex items-center gap-2 rounded-xl border border-slate-600 px-4 py-2 text-sm font-semibold"><ArrowLeft className="h-4 w-4" /> Perfis</button></header>
    <section className="mx-auto mt-7 grid max-w-7xl gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card valor={brl.format(resumo.faturado)} texto="total faturado" cor="text-blue-700" /><Card valor={brl.format(resumo.pago)} texto="total pago" cor="text-emerald-700" /><Card valor={brl.format(resumo.pendente)} texto="a receber" cor="text-amber-700" /><Card valor={resumo.atrasadas} texto="faturas atrasadas" cor="text-red-700" /></section>
    <section className="mx-auto mt-5 flex max-w-7xl flex-col gap-3 rounded-2xl bg-blue-50 p-4 text-sm text-blue-900 sm:flex-row sm:items-center sm:justify-between"><span><TimerReset className="mr-2 inline h-4 w-4" />{mensagem}</span><button onClick={rodarMotor} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white">Rodar automação diária</button></section>
    <section className="mx-auto mt-6 grid max-w-7xl gap-5 xl:grid-cols-2"><PainelMedicoes itens={medicoes} aprovar={aprovar} gerar={gerarFatura} /><PainelFaturas itens={faturas} pagar={pagar} simular={setSimulacao} />{simulacao && <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><Calculator className="h-5 w-5 text-violet-600" /> Simulador de antecipação</h2><p className="mt-4 rounded-xl bg-violet-50 p-4 text-sm text-violet-900">{simulacao}</p><p className="mt-3 text-xs text-slate-500">Desconto: 0,05% ao dia · Aplicação simulada: 0,04% ao dia.</p></section>}<PainelRegua /></section><AutomacoesFaturamento />
  </main>;
}
function Card({ valor, texto, cor }: { valor: string | number; texto: string; cor: string }) { return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className={`text-2xl font-bold ${cor}`}>{valor}</p><p className="mt-1 text-sm text-slate-500">{texto}</p></div>; }
function PainelMedicoes({ itens, aprovar, gerar }: { itens: Medicao[]; aprovar: (id: string) => void; gerar: (m: Medicao) => void }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><FileCheck2 className="h-5 w-5 text-blue-600" /> Medições de obras</h2><div className="mt-4 space-y-3">{itens.map((m) => <div key={m.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between"><b className="text-sm">{m.obra}</b><span className={`rounded-full px-2 py-1 text-xs font-bold ${m.status === "Aprovada" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{m.status}</span></div><p className="mt-1 text-xs text-slate-500">{m.percentual}% executado · {m.responsavel} · Valor: {brl.format(m.contrato * m.percentual / 100)}</p><div className="mt-3 flex gap-2">{m.status === "Rascunho" && <button onClick={() => aprovar(m.id)} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-bold text-white"><Check className="mr-1 inline h-3.5 w-3.5" /> Aprovar</button>}{m.status === "Aprovada" && <button onClick={() => gerar(m)} className="rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-bold text-white"><BadgeDollarSign className="mr-1 inline h-3.5 w-3.5" /> Gerar fatura</button>}</div></div>)}</div></section>; }
function PainelFaturas({ itens, pagar, simular }: { itens: Fatura[]; pagar: (id: string) => void; simular: (texto: string) => void }) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><BadgeDollarSign className="h-5 w-5 text-emerald-600" /> Faturas e recebimentos</h2><div className="mt-4 space-y-3">{itens.map((f) => { const acrescimo = f.status === "Atrasada" ? f.valor * (0.02 + 0.00033 * f.diasAtraso) : 0; return <div key={f.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between"><b className="text-sm">{f.obra}</b><span className={`rounded-full px-2 py-1 text-xs font-bold ${f.status === "Paga" ? "bg-emerald-100 text-emerald-700" : f.status === "Atrasada" ? "bg-red-100 text-red-700" : "bg-blue-100 text-blue-700"}`}>{f.status}</span></div><p className="mt-1 text-xs text-slate-500">Vencimento: {f.vencimento} · {brl.format(f.valor)}{f.status === "Atrasada" && ` · ${f.diasAtraso} dias de atraso`}</p>{f.status === "Atrasada" && <p className="mt-1 text-xs font-bold text-red-700">Multa + juros: {brl.format(acrescimo)} · Atualizado: {brl.format(f.valor + acrescimo)}</p>}<div className="mt-3 flex flex-wrap gap-2">{f.status !== "Paga" && <button onClick={() => pagar(f.id)} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-bold text-white">Registrar pagamento</button>}{f.status === "Emitida" && <button onClick={() => { const dias = 10; const desconto = f.valor * 0.0005 * dias; const aplicado = f.valor * (1 + 0.0004 * dias); simular(`Antecipar em ${dias} dias: receber ${brl.format(f.valor - desconto)} hoje. Aguardar e aplicar: projeção de ${brl.format(aplicado)}. Recomendação: aguardar e aplicar.`); }} className="rounded-lg bg-violet-100 px-3 py-1.5 text-xs font-bold text-violet-700">Simular antecipação</button>}</div></div>; })}</div></section>; }
function PainelRegua() { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="flex items-center gap-2 font-bold"><Send className="h-5 w-5 text-amber-600" /> Régua de cobrança automática</h2><div className="mt-4 space-y-2 text-sm"><p className="rounded-lg bg-slate-50 p-3">5 dias antes — Lembrete preventivo: fatura vence em 5 dias.</p><p className="rounded-lg bg-slate-50 p-3">1 dia antes — Lembrete preventivo: fatura vence amanhã.</p><p className="rounded-lg bg-amber-50 p-3 text-amber-800">No vencimento — Aviso de vencimento.</p><p className="rounded-lg bg-red-50 p-3 text-red-800">1 dia após — Cobrança: juros e multa começam a incidir.</p><p className="rounded-lg bg-red-50 p-3 text-red-800">10 dias após — Escalar para cobrança formal.</p></div></section>; }
