import { useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, BriefcaseBusiness, CalendarClock, CircleDollarSign, ShieldCheck, X } from "lucide-react";
import { META_MENSAL_NECS, VALOR_REFERENCIA_NEC, mockBloqueados, mockMarcos, mockObras, mockScoreEquipes, mockStopWork, semaforoFinanceiro, type Obra, type Semaforo } from "@/data/mockGerencia";
import { faturasIniciais, historicoInadimplencia, medicoesIniciais, resumoCobranca } from "@/data/faturamentoService";

type Categoria = "financeiro" | "cronograma" | "seguranca" | "comercial";
type Props = { onVoltar: () => void };
const moeda = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
const semaforoClasse: Record<Semaforo, string> = { ok: "bg-emerald-100 text-emerald-700", atencao: "bg-amber-100 text-amber-700", critico: "bg-red-100 text-red-700" };
const semaforoTexto: Record<Semaforo, string> = { ok: "OK", atencao: "ATENÇÃO", critico: "CRÍTICO" };

export function GerenciaGeralDashboard({ onVoltar }: Props) {
  const [janelas, setJanelas] = useState<Categoria[]>([]);
  const [obraAberta, setObraAberta] = useState<Obra | null>(null);
  const abrir = (categoria: Categoria) => setJanelas((atual) => atual.includes(categoria) ? atual : [...atual, categoria]);
  const fechar = (categoria: Categoria) => setJanelas((atual) => atual.filter((item) => item !== categoria));
  const alertas = useMemo(() => mockObras.filter((obra) => semaforoFinanceiro(obra) !== "ok").length + mockBloqueados.length + mockStopWork.filter((item) => item.status === "Parado").length, []);
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-800 sm:p-8">
    <header className="mx-auto flex max-w-7xl flex-col gap-4 rounded-3xl bg-slate-900 p-6 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><img src="/logo-eg.jpeg" alt="Logo EG" className="h-16 w-16 rounded-xl bg-white object-contain p-1" /><div><p className="text-xs font-bold tracking-[0.2em] text-amber-300">ELETROGESTOR</p><h1 className="mt-2 text-3xl font-bold">Gerência Geral</h1><p className="mt-1 text-sm text-slate-300">Visão consolidada — dados demonstrativos, somente leitura.</p></div></div><button onClick={onVoltar} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-600 px-4 py-2 text-sm font-semibold hover:bg-slate-800"><ArrowLeft className="h-4 w-4" /> Perfis</button></header>
    <section className="mx-auto mt-7 max-w-7xl"><PainelMensalNECs /><DesempenhoFaturamento /><div className="mb-5 mt-7 flex items-center justify-between"><div><h2 className="text-xl font-bold">Centro de decisão</h2><p className="text-sm text-slate-500">Clique em uma categoria para abrir seus indicadores.</p></div><span className="rounded-full bg-red-100 px-3 py-1 text-sm font-bold text-red-700">{alertas} alertas</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><CardCategoria titulo="Financeiro" texto="Custos, margem e faturamento" icone={<CircleDollarSign />} cor="bg-emerald-600" onClick={() => abrir("financeiro")} /><CardCategoria titulo="Cronograma" texto="Avanço, marcos e atrasos" icone={<CalendarClock />} cor="bg-blue-600" onClick={() => abrir("cronograma")} /><CardCategoria titulo="Segurança" texto="Incidentes e bloqueios" icone={<ShieldCheck />} cor="bg-amber-500" onClick={() => abrir("seguranca")} /><CardCategoria titulo="Comercial / Pipeline" texto="Carteira em NECs e score de equipes" icone={<BriefcaseBusiness />} cor="bg-violet-600" onClick={() => abrir("comercial")} /></div></section>
    <div className="mx-auto mt-6 grid max-w-7xl gap-5 xl:grid-cols-2">{janelas.map((categoria) => <Janela key={categoria} categoria={categoria} onFechar={() => fechar(categoria)} onObra={setObraAberta} />)}</div>{obraAberta && <DetalheObra obra={obraAberta} onFechar={() => setObraAberta(null)} />}
  </main>;
}

function DesempenhoFaturamento() {
  const resumo = resumoCobranca();
  const risco = [...medicoesIniciais.filter((m) => m.diasParada > 10).map((m) => ({ obra: m.obra, motivo: `Medição parada há ${m.diasParada} dias`, valor: m.contrato * m.percentual / 100 })), ...faturasIniciais.filter((f) => f.diasAtraso > 10).map((f) => ({ obra: f.obra, motivo: `Fatura atrasada há ${f.diasAtraso} dias`, valor: f.valor }))].sort((a, b) => b.valor - a.valor);
  const cruzado = medicoesIniciais.map((m) => { const f = faturasIniciais.find((item) => item.obra === m.obra); return { obra: m.obra, medido: m.percentual, faturado: f?.percentualFaturado ?? 0, pago: f?.percentualPago ?? 0 }; });
  const pontos = historicoInadimplencia.map((v, i) => `${i * 28},${110 - v * 8}`).join(" ");
  return <section className="mt-7 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div><p className="text-xs font-bold tracking-wider text-emerald-700">DADOS DO SERVIÇO DE FATURAMENTO</p><h2 className="mt-1 text-xl font-bold">Desempenho de Faturamento e Cobrança</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Indicador numero={`${resumo.recuperacao.toFixed(0)}%`} texto="recuperação de faturas atrasadas" /><Indicador numero={`${resumo.tempoMedio} dias`} texto="tempo médio vencimento até pagamento" /><Indicador numero={`${moeda.format(resumo.pendente)} / ${moeda.format(resumo.pago)}`} texto="pendente vs pago no mês" /><Indicador numero={`${resumo.faixas[0]} · ${resumo.faixas[1]} · ${resumo.faixas[2]}`} texto="atrasos: 1-10 · 11-30 · 30+ dias" /></div><div className="mt-6 grid gap-5 xl:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold">Evolução mensal da inadimplência</h3><p className="text-xs text-slate-500">Últimos 12 meses · percentual</p><svg viewBox="0 0 320 120" className="mt-3 h-32 w-full"><polyline points={pontos} fill="none" stroke="#7c3aed" strokeWidth="4" strokeLinejoin="round" /><line x1="0" y1="110" x2="310" y2="110" stroke="#cbd5e1" /></svg><p className="text-xs text-slate-500">Out · Nov · Dez · Jan · Fev · Mar · Abr · Mai · Jun · Jul · Ago · Set</p></div><div><h3 className="font-bold">Obras em risco financeiro</h3><div className="mt-3 space-y-2">{risco.map((item) => <div key={`${item.obra}-${item.motivo}`} className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><b>{item.obra}</b><span className="float-right font-bold">{moeda.format(item.valor)}</span><p className="mt-1 text-xs">{item.motivo}</p></div>)}{risco.length === 0 && <p className="text-sm text-slate-500">Sem riscos identificados.</p>}</div></div></div><div className="mt-5 overflow-x-auto"><h3 className="mb-3 font-bold">Indicador cruzado por obra</h3><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-2">Obra</th><th className="p-2">% medido</th><th className="p-2">% faturado</th><th className="p-2">% pago</th><th className="p-2">Alerta</th></tr></thead><tbody>{cruzado.map((item) => <tr key={item.obra} className="border-b"><td className="p-2 font-bold">{item.obra}</td><td className="p-2">{item.medido}%</td><td className="p-2">{item.faturado}%</td><td className="p-2">{item.pago}%</td><td className="p-2 text-amber-700">{item.medido > item.faturado ? "Medição não acompanhada por faturamento" : "OK"}</td></tr>)}</tbody></table></div></section>;
}

function PainelMensalNECs() {
  const executados = mockObras.reduce((total, obra) => total + obra.necsExecutados, 0);
  const saldo = Math.max(0, META_MENSAL_NECS - executados);
  const emExecucao = mockObras.filter((obra) => obra.status === "em_execucao");
  const concluidas = mockObras.filter((obra) => obra.status === "concluida");
  const percentual = (executados / META_MENSAL_NECS) * 100;
  return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold tracking-wider text-violet-700">CARTEIRA MENSAL ENEL</p><h2 className="mt-1 text-xl font-bold">Meta: {META_MENSAL_NECS.toLocaleString("pt-BR")} NECs</h2><p className="text-sm text-slate-500">1 NEC ≈ R$ {VALOR_REFERENCIA_NEC.toLocaleString("pt-BR")} (referência; a gestão é em NECs).</p></div><span className="rounded-full bg-violet-100 px-3 py-1 text-sm font-bold text-violet-800">{percentual.toFixed(1)}% executado</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Indicador numero={`${executados.toLocaleString("pt-BR")} NECs`} texto="executados no mês" /><Indicador numero={`${saldo.toLocaleString("pt-BR")} NECs`} texto="a executar até o fim do mês" /><Indicador numero={`${emExecucao.length} / ${concluidas.length}`} texto="obras em execução / executadas" /></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-violet-600 transition-all" style={{ width: `${Math.min(percentual, 100)}%` }} /></div><div className="mt-5 grid gap-3 md:grid-cols-2"><ListaObras titulo="Obras em execução" obras={emExecucao} /><ListaObras titulo="Obras executadas" obras={concluidas} /></div></section>;
}

function ListaObras({ titulo, obras }: { titulo: string; obras: Obra[] }) { return <div><h3 className="mb-2 text-sm font-bold">{titulo}</h3>{obras.map((obra) => <div key={obra.codigo} className="mb-2 rounded-lg bg-slate-50 p-3 text-sm"><div className="flex justify-between gap-2"><b>{obra.codigo}</b><span className="font-bold text-violet-700">{obra.necsExecutados.toLocaleString("pt-BR")} / {obra.necsPlanejados.toLocaleString("pt-BR")} NECs</span></div><p className="mt-1 text-xs text-slate-500">{obra.nome} · {obra.equipe}</p></div>)}{obras.length === 0 && <p className="text-sm text-slate-500">Nenhuma obra nesta situação.</p>}</div>; }

function CardCategoria({ titulo, texto, icone, cor, onClick }: { titulo: string; texto: string; icone: ReactNode; cor: string; onClick: () => void }) { return <button onClick={onClick} className="group rounded-2xl bg-white p-5 text-left shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-lg"><span className={`mb-5 inline-flex rounded-xl p-3 text-white ${cor}`}>{icone}</span><h3 className="font-bold">{titulo}</h3><p className="mt-1 text-sm text-slate-500">{texto}</p><span className="mt-5 inline-block text-sm font-bold text-slate-700 group-hover:text-amber-600">Abrir painel →</span></button>; }
function Janela({ categoria, onFechar, onObra }: { categoria: Categoria; onFechar: () => void; onObra: (obra: Obra) => void }) { const titulos: Record<Categoria, string> = { financeiro: "💰 Financeiro", cronograma: "📅 Cronograma", seguranca: "🦺 Segurança do Trabalho", comercial: "📈 Comercial / Pipeline" }; return <section className="overflow-hidden rounded-2xl bg-white shadow-lg ring-1 ring-slate-200"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-bold">{titulos[categoria]}</h2><button onClick={onFechar} className="rounded-lg p-1 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5" /></button></header><div className="max-h-[520px] overflow-auto p-5">{categoria === "financeiro" && <Financeiro onObra={onObra} />}{categoria === "cronograma" && <Cronograma onObra={onObra} />}{categoria === "seguranca" && <Seguranca />}{categoria === "comercial" && <Comercial />}</div></section>; }
function Financeiro({ onObra }: { onObra: (obra: Obra) => void }) { return <div className="space-y-3"><p className="text-sm text-slate-500">Desvio orçamentário, projeção e margem por obra.</p>{mockObras.map((obra) => { const desvio = obra.custoPrevisto ? ((obra.custoRealizado - obra.custoPrevisto) / obra.custoPrevisto) * 100 : 0; const projetado = obra.avancoRealizado ? obra.custoRealizado / (obra.avancoRealizado / 100) : obra.custoPrevisto; const status = semaforoFinanceiro(obra); return <button key={obra.codigo} onClick={() => onObra(obra)} className="w-full rounded-xl border border-slate-200 p-4 text-left hover:border-amber-400"><div className="flex justify-between gap-2"><b className="text-sm">{obra.codigo}</b><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${semaforoClasse[status]}`}>{semaforoTexto[status]}</span></div><p className="mt-1 text-xs text-slate-500">{obra.nome}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>Desvio: <b>{desvio.toFixed(1)}%</b></span><span>Margem: <b>{obra.valorContrato ? (((obra.valorContrato - obra.custoRealizado) / obra.valorContrato) * 100).toFixed(1) : 0}%</b></span><span className="col-span-2">Custo projetado: <b>{moeda.format(projetado)}</b></span></div></button>; })}<h3 className="pt-2 text-sm font-bold">Pendências de faturamento</h3>{mockMarcos.filter((m) => m.concluido && !m.faturado).map((m) => <p key={m.marco} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800"><b>{m.obra}</b> — {m.marco}: gerar medição de faturamento.</p>)}</div>; }
function Cronograma({ onObra }: { onObra: (obra: Obra) => void }) { return <div className="space-y-3">{mockObras.map((obra) => { const diferenca = obra.avancoRealizado - obra.avancoPrevisto; const risco = obra.avancoRealizado < 100 && 100 - obra.avancoRealizado > 30; return <button key={obra.codigo} onClick={() => onObra(obra)} className="w-full rounded-xl border border-slate-200 p-4 text-left hover:border-blue-400"><div className="flex justify-between"><b className="text-sm">{obra.codigo}</b>{risco && <span className="text-xs font-bold text-red-600">RISCO DE ATRASO</span>}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${obra.avancoRealizado}%` }} /></div><p className="mt-2 text-xs text-slate-600">Previsto <b>{obra.avancoPrevisto}%</b> · Realizado <b>{obra.avancoRealizado}%</b> · Diferença <b>{diferenca} p.p.</b></p></button>; })}<h3 className="pt-2 text-sm font-bold">Marcos atrasados</h3>{mockMarcos.filter((m) => !m.concluido).map((m) => <p key={m.marco} className="rounded-lg bg-red-50 p-3 text-sm text-red-700"><b>{m.obra}</b> — {m.marco}: {m.diasAtraso} dias de atraso.</p>)}</div>; }
function Seguranca() { return <div className="space-y-4"><div className="grid grid-cols-2 gap-3"><Indicador numero="1" texto="incidente registrável" /><Indicador numero="40" texto="dias sem incidente" /><Indicador numero="2,88 h" texto="CAIDI (proxy)" /><Indicador numero="2" texto="trabalhadores bloqueados" /></div><h3 className="text-sm font-bold">Bloqueio automático de alocação</h3>{mockBloqueados.map((item) => <p key={item.trabalhador} className="rounded-lg bg-red-50 p-3 text-sm text-red-700"><b>{item.trabalhador}</b> · {item.equipe}<br />{item.motivos.join(", ")}</p>)}<h3 className="text-sm font-bold">Stop Work</h3>{mockStopWork.map((item) => <p key={item.obra} className="rounded-lg border border-slate-200 p-3 text-sm"><b>{item.obra}</b> — {item.motivo}<span className={`ml-2 text-xs font-bold ${item.status === "Parado" ? "text-red-600" : "text-emerald-600"}`}>{item.status}</span></p>)}</div>; }
function Comercial() { const carteira = mockObras.reduce((total, obra) => total + obra.necsPlanejados, 0); const scores = [...mockScoreEquipes].sort((a, b) => (b.prazo + b.qualidade + b.seguranca) - (a.prazo + a.qualidade + a.seguranca)); return <div className="space-y-4"><div className="rounded-xl bg-violet-50 p-4"><p className="text-xs font-bold uppercase text-violet-700">Carteira planejada</p><p className="mt-1 text-2xl font-bold text-violet-950">{carteira.toLocaleString("pt-BR")} NECs</p><p className="mt-1 text-xs text-violet-700">Meta mensal Enel: {META_MENSAL_NECS.toLocaleString("pt-BR")} NECs</p></div><div className="space-y-2">{["proposta", "contratada", "em_execucao", "concluida"].map((status) => <p key={status} className="flex justify-between rounded-lg border border-slate-200 p-3 text-sm capitalize"><span>{status.replace("_", " ")}</span><b>{mockObras.filter((o) => o.status === status).reduce((s, o) => s + o.necsPlanejados, 0).toLocaleString("pt-BR")} NECs</b></p>)}</div><h3 className="text-sm font-bold">Scorecard mensal</h3>{scores.map((s) => <p key={s.equipe} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><b>{s.equipe}</b><span>Prazo {s.prazo} · Qualidade {s.qualidade} · Segurança {s.seguranca} · <b>{((s.prazo + s.qualidade + s.seguranca) / 3).toFixed(2)}</b></span></p>)}</div>; }
function Indicador({ numero, texto }: { numero: string; texto: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-bold">{numero}</p><p className="text-xs text-slate-500">{texto}</p></div>; }
function DetalheObra({ obra, onFechar }: { obra: Obra; onFechar: () => void }) { const status = semaforoFinanceiro(obra); const marcos = mockMarcos.filter((m) => m.obra === obra.codigo); return <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/45 p-4"><section className="w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b p-5"><div><p className="text-xs font-bold text-amber-600">DETALHE DA OBRA</p><h2 className="mt-1 font-bold">{obra.codigo}</h2><p className="text-sm text-slate-500">{obra.nome} · {obra.equipe}</p></div><button onClick={onFechar}><X /></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><b>Financeiro</b><p className="mt-2 text-sm">Previsto: {moeda.format(obra.custoPrevisto)}</p><p className="text-sm">Realizado: {moeda.format(obra.custoRealizado)}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-xs font-bold ${semaforoClasse[status]}`}>{semaforoTexto[status]}</span></div><div className="rounded-xl bg-slate-50 p-4"><b>Cronograma</b><p className="mt-2 text-sm">Previsto: {obra.avancoPrevisto}%</p><p className="text-sm">Realizado: {obra.avancoRealizado}%</p></div><div className="sm:col-span-2"><b className="text-sm">Marcos</b>{marcos.length ? marcos.map((m) => <p key={m.marco} className="mt-2 rounded-lg border p-3 text-sm">{m.marco} — {m.concluido ? "Concluído" : `${m.diasAtraso} dias em atraso`}</p>) : <p className="mt-2 text-sm text-slate-500">Sem marcos cadastrados.</p>}</div></div></section></div>; }
