import { useMemo, useState } from "react";
import { Bot, KeyRound, LockKeyhole, Save, ShieldCheck, SlidersHorizontal } from "lucide-react";

type BotItem = { id: string; nome: string; obra: string; ativo: boolean };
type LogItem = { data: string; bot: string; acao: string; entidade: string; antes: string; depois: string; responsavel: string };

const botsIniciais: BotItem[] = [
  { id: "cobranca", nome: "Cobrança automática", obra: "Global", ativo: true },
  { id: "juros", nome: "Juros e multa por atraso", obra: "Global", ativo: true },
  { id: "antecipacao", nome: "Desconto por antecipação", obra: "DMP/A.SUL.25.00420", ativo: true },
  { id: "regua", nome: "Régua de cobrança", obra: "Global", ativo: false },
];
const logsIniciais: LogItem[] = [
  { data: "2026-09-17 07:00", bot: "Juros e multa por atraso", acao: "Recalculou valor", entidade: "FAT-00087", antes: "R$ 80.000,00", depois: "R$ 82.664,00", responsavel: "sistema" },
  { data: "2026-09-17 07:00", bot: "Cobrança automática", acao: "Enviou lembrete", entidade: "FAT-00103", antes: "Pendente", depois: "Lembrete enviado", responsavel: "sistema" },
  { data: "2026-09-16 16:34", bot: "Desconto por antecipação", acao: "Simulou antecipação", entidade: "DMP/A.SUL.25.00420", antes: "R$ 30.000,00", depois: "R$ 29.850,00", responsavel: "Maria Souza" },
];

export function GovernancaAutomacoes() {
  const [bots, setBots] = useState(botsIniciais);
  const [parametros, setParametros] = useState({ multa: 2, juros: 0.033, tetoDesconto: 5, prazo: 30 });
  const [mensagem, setMensagem] = useState("");
  const [filtros, setFiltros] = useState({ data: "", bot: "", obra: "" });
  const [credenciais, setCredenciais] = useState({ pix: "...7K9P", whatsapp: "...A4D2", sms: "...91XZ" });
  const [novasChaves, setNovasChaves] = useState({ pix: "", whatsapp: "", sms: "" });
  const logs = useMemo(() => logsIniciais.filter((log) => (!filtros.data || log.data.startsWith(filtros.data)) && (!filtros.bot || log.bot === filtros.bot) && (!filtros.obra || log.entidade.toLowerCase().includes(filtros.obra.toLowerCase()))), [filtros]);
  const salvarParametros = () => { if (parametros.multa < 0 || parametros.multa > 20 || parametros.juros < 0 || parametros.juros > 2 || parametros.tetoDesconto < 0 || parametros.tetoDesconto > 30 || parametros.prazo < 1 || parametros.prazo > 180) { setMensagem("Revise os limites: multa 0-20%, juros 0-2% ao dia, desconto 0-30% e prazo 1-180 dias."); return; } setMensagem("Parâmetros salvos. O teto de desconto passa a limitar o Faturamento automaticamente."); };
  const salvarChave = (tipo: keyof typeof credenciais) => { const chave = novasChaves[tipo]; if (chave.length < 4) return; setCredenciais((atual) => ({ ...atual, [tipo]: `...${chave.slice(-4)}` })); setNovasChaves((atual) => ({ ...atual, [tipo]: "" })); };
  return <section className="mx-auto mt-6 max-w-7xl rounded-3xl border border-violet-200 bg-violet-50/50 p-5 sm:p-7"><div className="flex items-start gap-3"><span className="rounded-xl bg-violet-600 p-3 text-white"><Bot className="h-6 w-6" /></span><div><p className="text-xs font-bold tracking-[0.16em] text-violet-700">EXCLUSIVO DO ADMINISTRADOR</p><h2 className="mt-1 text-2xl font-bold">Governança de Automações</h2><p className="mt-1 text-sm text-slate-600">Controle central dos bots financeiros, regras e integrações do sistema.</p></div></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="flex items-center gap-2 font-bold"><Bot className="h-5 w-5 text-violet-600" /> Bots ativos</h3><div className="mt-4 space-y-2">{bots.map((bot) => <div key={bot.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><span><b className="block text-sm">{bot.nome}</b><small className="text-slate-500">Escopo: {bot.obra}</small></span><button onClick={() => setBots((lista) => lista.map((item) => item.id === bot.id ? { ...item, ativo: !item.ativo } : item))} className={`rounded-full px-3 py-1.5 text-xs font-bold ${bot.ativo ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{bot.ativo ? "Ativo" : "Inativo"}</button></div>)}</div></section>
      <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="flex items-center gap-2 font-bold"><SlidersHorizontal className="h-5 w-5 text-amber-600" /> Parâmetros globais</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Campo label="Multa por atraso (%)" valor={parametros.multa} min={0} max={20} passo={0.1} alterar={(valor) => setParametros({ ...parametros, multa: valor })} /><Campo label="Juros de mora ao dia (%)" valor={parametros.juros} min={0} max={2} passo={0.001} alterar={(valor) => setParametros({ ...parametros, juros: valor })} /><Campo label="Teto de desconto (%)" valor={parametros.tetoDesconto} min={0} max={30} passo={0.1} alterar={(valor) => setParametros({ ...parametros, tetoDesconto: valor })} /><Campo label="Vencimento padrão (dias)" valor={parametros.prazo} min={1} max={180} passo={1} alterar={(valor) => setParametros({ ...parametros, prazo: valor })} /></div><button onClick={salvarParametros} className="mt-4 rounded-lg bg-violet-700 px-3 py-2 text-xs font-bold text-white"><Save className="mr-1 inline h-3.5 w-3.5" /> Salvar parâmetros</button>{mensagem && <p className="mt-3 rounded-lg bg-violet-50 p-3 text-sm text-violet-800">{mensagem}</p>}</section>
      <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 xl:col-span-2"><h3 className="flex items-center gap-2 font-bold"><ShieldCheck className="h-5 w-5 text-slate-700" /> Logs de auditoria das automações</h3><div className="mt-4 grid gap-2 sm:grid-cols-3"><input type="date" value={filtros.data} onChange={(e) => setFiltros({ ...filtros, data: e.target.value })} className="rounded-lg border p-2 text-sm" /><select value={filtros.bot} onChange={(e) => setFiltros({ ...filtros, bot: e.target.value })} className="rounded-lg border p-2 text-sm"><option value="">Todos os bots</option>{bots.map((b) => <option key={b.id}>{b.nome}</option>)}</select><input placeholder="Filtrar obra/fatura" value={filtros.obra} onChange={(e) => setFiltros({ ...filtros, obra: e.target.value })} className="rounded-lg border p-2 text-sm" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-100 text-slate-600"><tr><th className="p-2">Data</th><th className="p-2">Bot</th><th className="p-2">Ação</th><th className="p-2">Entidade</th><th className="p-2">Antes</th><th className="p-2">Depois</th><th className="p-2">Responsável</th></tr></thead><tbody>{logs.map((log, i) => <tr key={i} className="border-b"><td className="p-2">{log.data}</td><td className="p-2">{log.bot}</td><td className="p-2">{log.acao}</td><td className="p-2">{log.entidade}</td><td className="p-2">{log.antes}</td><td className="p-2">{log.depois}</td><td className="p-2">{log.responsavel}</td></tr>)}{logs.length === 0 && <tr><td colSpan={7} className="p-4 text-center text-slate-500">Nenhum log encontrado.</td></tr>}</tbody></table></div></section>
      <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 xl:col-span-2"><h3 className="flex items-center gap-2 font-bold"><LockKeyhole className="h-5 w-5 text-blue-600" /> Credenciais de integrações</h3><p className="mt-1 text-sm text-slate-500">Chaves são mascaradas. Em produção, o valor deve ser criptografado no backend; a tela só mostra os últimos quatro caracteres.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{(["pix", "whatsapp", "sms"] as const).map((tipo) => <div key={tipo} className="rounded-xl bg-slate-50 p-4"><b className="text-sm">{tipo === "pix" ? "PIX Automático" : tipo === "whatsapp" ? "WhatsApp Business API" : "SMS"}</b><p className="mt-2 font-mono text-sm text-slate-600">Chave salva: {credenciais[tipo]}</p><input type="password" value={novasChaves[tipo]} onChange={(e) => setNovasChaves({ ...novasChaves, [tipo]: e.target.value })} placeholder="Nova chave" className="mt-3 w-full rounded-lg border bg-white p-2 text-sm" /><button onClick={() => salvarChave(tipo)} className="mt-2 rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white"><KeyRound className="mr-1 inline h-3.5 w-3.5" /> Atualizar</button></div>)}</div></section>
    </div></section>;
}
function Campo({ label, valor, min, max, passo, alterar }: { label: string; valor: number; min: number; max: number; passo: number; alterar: (valor: number) => void }) { return <label className="text-sm">{label}<input type="number" value={valor} min={min} max={max} step={passo} onChange={(e) => alterar(Number(e.target.value))} className="mt-1 w-full rounded-lg border p-2" /><small className="text-slate-500">Limite: {min} a {max}</small></label>; }
