import { ArrowLeft, ClipboardList, Info, Settings2 } from "lucide-react";
import type { Perfil } from "@/data/perfis";

type Props = { perfil: Perfil; onVoltar: () => void };

export function PerfilDashboard({ perfil, onVoltar }: Props) {
  const Icone = perfil.icone;
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-800 sm:p-8"><header className="mx-auto flex max-w-5xl flex-col gap-4 rounded-3xl bg-slate-900 p-6 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><img src="/logo-eg.jpeg" alt="Logo EG" className="h-16 w-16 rounded-xl bg-white object-contain p-1" /><div><p className="text-xs font-bold tracking-[0.2em] text-amber-300">ELETROGESTOR</p><h1 className="mt-2 text-3xl font-bold">{perfil.nome}</h1><p className="mt-1 text-sm text-slate-300">{perfil.descricao}</p></div></div><button onClick={onVoltar} className="inline-flex items-center gap-2 rounded-xl border border-slate-600 px-4 py-2 text-sm font-semibold hover:bg-slate-800"><ArrowLeft className="h-4 w-4" /> Perfis</button></header><section className="mx-auto mt-7 max-w-5xl rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><span className="inline-flex rounded-2xl bg-amber-100 p-4"><Icone className="h-8 w-8 text-amber-600" /></span><h2 className="mt-5 text-xl font-bold">Área de {perfil.nome}</h2><p className="mt-2 max-w-2xl text-slate-600">Você entrou no perfil selecionado sem tela de login. Este espaço está pronto para receber as rotinas específicas deste módulo.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><Info className="h-5 w-5 text-blue-600" /><h3 className="mt-3 font-bold">Acesso liberado</h3><p className="mt-1 text-sm text-slate-500">Perfil ativo: {perfil.categoria}.</p></div><div className="rounded-xl bg-slate-50 p-4"><ClipboardList className="h-5 w-5 text-emerald-600" /><h3 className="mt-3 font-bold">Próxima configuração</h3><p className="mt-1 text-sm text-slate-500">Adicione os fluxos e dados próprios desta área.</p></div></div><button onClick={onVoltar} className="mt-7 inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white"><Settings2 className="h-4 w-4" /> Trocar perfil</button></section></main>;
}
